title: Xuedong Shang
description: My Personal Blog
author: Xuedong Shang (商雪岽 字雨山)
logo: /static/img/avatar.jpg
github: https://github.com/xuedong
about: Machine Learner

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: xuedong
google_analytics: UA-109522196-1

share:
  twitter_username: AbsolutSamuel
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
